/**
 * OGCard — Homepage Open Graph image design.
 *
 * Previewed here at exact 1200×630 so the design can be approved before
 * the image is generated by Next.js Satori. Iterate here, then ship.
 *
 * Note: Satori has minor rendering differences from browsers (no pseudo-elements,
 * limited CSS support) but the visual should be very close to the final output.
 * Victor Mono is loaded via @fontsource in the browser preview.
 */

import type { Meta, StoryObj } from '@storybook/nextjs-vite'
import OGCard, { OG_SIZE } from '@/components/OGCard'

const meta: Meta<typeof OGCard> = {
  title: 'Design System/OG Card',
  component: OGCard,
  parameters: {
    layout: 'fullscreen',
    backgrounds: { disable: true },
    viewport: {
      viewports: {
        og: {
          name: 'OG Image (1200×630)',
          styles: { width: '1200px', height: '630px' },
        },
      },
      defaultViewport: 'og',
    },
  },
  args: {
    tagline: 'I make websites and things',
  },
}

export default meta
type Story = StoryObj<typeof OGCard>

/**
 * The homepage OG image at exact production dimensions (1200×630).
 * Tagline is the live WordPress site description.
 */
export const Default: Story = {
  name: `Homepage OG image — ${OG_SIZE.width}×${OG_SIZE.height}`,
  render: ({ tagline }) => (
    <div style={{ width: OG_SIZE.width, height: OG_SIZE.height, overflow: 'hidden', fontFamily: 'Victor Mono, monospace' }}>
      <OGCard tagline={tagline} />
    </div>
  ),
}
